site_name: Documentação PyTest

site_url: https://pytest.com/
site_description: Documentação do PyTest, para o trabalho da disciplina de Desenvolvimento Web.
site_author: Pedro Fonseca Rodrigues de Sousa, Richard Stf, Vitor Pires Zini

repo_name: DocumentacaoPyTest
repo_url: https://github.com/PedroFonseca08/DocumentacaoPyTest

nav:
  - Introdução: index.md
  - Como usar: howToUse.md
  - Exemplos: examples.md
  - Contribuidores: contributors.md
  - Recursos: recursos.md
theme:
  name: material
  language: pt-BR
  palette: 
    - scheme: default
      primary: pink       
      accent: purple  
      toggle:
        icon: material/brightness-7     
        name: Trocar para modo escuro   
    - scheme: slate 
      primary: purple
      accent: pink
      toggle:
        icon: material/brightness-4 
        name: Trocar para modo claro
  features:
    - content.tabs.link             
    - content.code.copy             
  extra:
    generator: false
